version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allomotos_api
    ports:
      - "3200:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3307
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=allomotos
    volumes:
      - .:/app

  db:
    image: mysql:9.0.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allomotos
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: athena

volumes:
  mysqldata:
