version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motos_api
    ports:
      - "3200:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=motos
    volumes:
      - .:/app

  db:
    image: mysql:9.0.0
    container_name: mysql_motos_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: motos
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 5

  adminer:
    image: adminer:4.8.1-standalone
    container_name: adminer_motos
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysqldata:
    name: moto_data_persist_db
    driver: local
